project_name: flog

builds:
  - id: cli
    binary: flog
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    builds:
      - cli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - Update README.md
      - Merge pull request
      - Merge branch

brews:
  - name: flog
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: mingrammer
      email: mingrammer@gmail.com
    homepage: https://github.com/mingrammer/flog
    description: "A fake log generator for common log formats"
    install: bin.install "flog"
